### ISSUE TITLE
最近变动要求数据库密码不能包含? @ ^ $，但是这是密码要求，怎么办？

### ISSUE THREAD

**Issue by roytrack** [cookieY/Gemini#2]
![image](https://user-images.githubusercontent.com/3425315/71167223-41ede980-228f-11ea-801e-fa71678c4fe4.png)
这块内部有要求，必须有特殊字符，对于这块为什么要禁用特殊字符？

**Comment by cookieY** [comment]
由于这几个关键字会导致使用pt-osc时出现转义错误。如你不需要pt-osc 可以自行修改前端文件

**Comment by roytrack** [comment]
好的 多谢
